import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Rocket,
  Users,
  Target,
  Lightbulb,
  Building,
  DollarSign,
  Code,
  Palette,
  Megaphone,
  BarChart3,
  Briefcase,
  Heart,
  Star,
  TrendingUp,
  Award,
  CheckCircle,
  Circle,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  ChevronLeft,
  Plus,
  X,
  Save,
  RefreshCw,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  MoreHorizontal,
  ThumbsUp,
  MessageSquare,
  Handshake,
  Flag,
  Compass,
  Navigation,
  Sparkles,
  Crown,
  Gem,
  Trophy,
  Gift,
  Diamond,
  UserPlus,
  UserCheck,
  BookOpen,
  Shield,
  Lock,
  Unlock,
  Globe,
  Wifi,
  WifiOff,
  Download,
  Share2,
  Copy,
  Edit,
  Trash2,
  Archive,
  FolderOpen,
  Folder,
  File,
  FilePlus,
  FolderPlus,
  Grid3X3,
  List,
  Maximize2,
  Minimize2,
  Fullscreen,
  Brain,
  Cpu,
  Database,
  Server,
  Cloud,
  Smartphone,
  Tablet,
  Monitor,
  Headphones,
  Mic,
  MicOff,
  Phone,
  PhoneOff,
  Mail,
  MailOpen,
  Send,
  Paperclip,
  Bookmark,
  HeartHandshake,
  Users2,
  UserCircle,
  UserCheck2,
  UserX2,
  ZapOff,
  Battery,
  BatteryCharging,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  Activity,
  ActivitySquare,
  Square,
  CheckSquare,
  Video,
  VideoOff,
  Camera,
  CameraOff,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipForward,
  Rewind,
  Startup,
  Calendar,
  CalendarCheck,
  CalendarX,
  Clock,
  Timer,
  TimerReset,
  TimerOff,
  Stopwatch,
  AlarmClock,
  AlarmClockOff,
  Hourglass,
  TimerStart,
  TimerPause,
  TimerEnd,
  GraduationCap,
  Building as BuildingIcon,
  DollarSign as DollarSignIcon,
  Eye,
  EyeOff,
  Settings,
  HelpCircle,
  MapPin,
  Flag as FlagIcon,
  Compass as CompassIcon,
  Navigation as NavigationIcon,
  FileText,
  Image,
  Upload,
  Link,
  GitBranch,
  Terminal,
  Package,
  Layers,
  Box,
  Archive,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  Server as ServerIcon,
  Monitor as MonitorIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Headphones as HeadphonesIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Video as VideoIcon,
  VideoOff as VideoOffIcon,
  Camera as CameraIcon,
  CameraOff as CameraOffIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  SkipForward as SkipForwardIcon,
  Rewind as RewindIcon,
  FastForward as FastForwardIcon,
  Repeat as RepeatIcon,
  Radio as RadioIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  BellRing as BellRingIcon,
  Calendar as CalendarIcon,
  CalendarCheck as CalendarCheckIcon,
  CalendarX as CalendarXIcon,
  Clock as ClockIcon,
  Timer as TimerIcon,
  TimerReset as TimerResetIcon,
  TimerOff as TimerOffIcon,
  Stopwatch as StopwatchIcon,
  AlarmClock as AlarmClockIcon,
  AlarmClockOff as AlarmClockOffIcon,
  Hourglass as HourglassIcon,
  TimerStart as TimerStartIcon,
  TimerPause as TimerPauseIcon,
  TimerEnd as TimerEndIcon,
  FileText as FileTextIcon,
  Image as ImageIcon,
  Upload as UploadIcon,
  Link as LinkIcon,
  GitBranch as GitBranchIcon,
  Terminal as TerminalIcon,
  Package as PackageIcon,
  Layers as LayersIcon,
  Box as BoxIcon,
  Archive as ArchiveIcon,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  Server as ServerIcon,
  Monitor as MonitorIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Headphones as HeadphonesIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Video as VideoIcon,
  VideoOff as VideoOffIcon,
  Camera as CameraIcon,
  CameraOff as CameraOffIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  SkipForward as SkipForwardIcon,
  Rewind as RewindIcon,
  FastForward as FastForwardIcon,
  Repeat as RepeatIcon,
  Radio as RadioIcon,
  Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      Smartphone as SmartphoneIcon,
      Tablet as TabletIcon,
      Headphones as HeadphonesIcon,
      Mic as MicIcon,
      MicOff as MicOffIcon,
      Video as VideoIcon,
      VideoOff as VideoOffIcon,
      Camera as CameraIcon,
      CameraOff as CameraOffIcon,
      Volume2 as Volume2Icon,
      VolumeX as VolumeXIcon,
      Play as PlayIcon,
      Pause as PauseIcon,
      SkipForward as SkipForwardIcon,
      Rewind as RewindIcon,
      FastForward as FastForwardIcon,
      Repeat as RepeatIcon,
      Radio as RadioIcon,
      Bell as BellIcon,
      BellOff as BellOffIcon,
      BellRing as BellRingIcon,
      Calendar as CalendarIcon,
      CalendarCheck as CalendarCheckIcon,
      CalendarX as CalendarXIcon,
      Clock as ClockIcon,
      Timer as TimerIcon,
      TimerReset as TimerResetIcon,
      TimerOff as TimerOffIcon,
      Stopwatch as StopwatchIcon,
      AlarmClock as AlarmClockIcon,
      AlarmClockOff as AlarmClockOffIcon,
      Hourglass as HourglassIcon,
      TimerStart as TimerStartIcon,
      TimerPause as TimerPauseIcon,
      TimerEnd as TimerEndIcon,
      FileText as FileTextIcon,
      Image as ImageIcon,
      Upload as UploadIcon,
      Link as LinkIcon,
      GitBranch as GitBranchIcon,
      Terminal as TerminalIcon,
      Package as PackageIcon,
      Layers as LayersIcon,
      Box as BoxIcon,
      Archive as ArchiveIcon,
      Database as DatabaseIcon,
      Cloud as CloudIcon,
      Server as ServerIcon,
      Monitor as MonitorIcon,
      <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
                  <Startup className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h1 className="text-xl font-semibold">Startup Stage & Commitment</h1>
                  <p className="text-sm text-muted-foreground">
                    Step {currentStep + 1} of {onboardingSteps.length}: {onboardingSteps[currentStep].title}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Step Progress */}
          <div className="bg-white border-b">
            <div className="max-w-7xl mx-auto px-6 py-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  {onboardingSteps.map((step, index) => (
                    <div key={step.id} className="flex items-center">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                        index <= currentStep ? 'bg-primary text-white' : 'bg-muted text-muted-foreground'
                      }`}>
                        {index < currentStep ? (
                          <CheckCircle className="w-4 h-4" />
                        ) : (
                          <span className="text-xs font-medium">{index + 1}</span>
                        )}
                      </div>
                      {index < onboardingSteps.length - 1 && (
                        <div className={`w-16 h-1 mx-2 ${
                          index < currentStep ? 'bg-primary' : 'bg-muted'
                        }`} />
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="max-w-4xl mx-auto px-6 py-8">
            <AnimatePresence mode="wait">
              <motion.div
                key={currentStep}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
              >
                {renderStepContent()}
              </motion.div>
            </AnimatePresence>

            {/* Navigation */}
            <div className="flex items-center justify-between mt-8 pt-8 border-t">
              <Button
                variant="outline"
                onClick={handlePrevious}
                disabled={currentStep === 0}
                className="gap-2"
              >
                <ChevronLeft className="w-4 h-4" />
                Previous
              </Button>
              
              <div className="flex items-center space-x-2">
                <Button
                  variant="outline"
                  onClick={() => {
                    // Save progress
                    toast({
                      title: "Progress saved",
                      description: "Your startup profile has been saved."
                    });
                  }}
                >
                  <Save className="w-4 h-4 mr-2" />
                  Save Progress
                </Button>
                
                <Button
                  onClick={handleNext}
                  disabled={isSaving}
                  className="gap-2"
                >
                  {isSaving ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      Saving...
                    </>
                  ) : currentStep === onboardingSteps.length - 1 ? (
                    <>
                      Complete
                      <CheckCircle className="w-4 h-4" />
                    </>
                  ) : (
                    <>
                      Next
                      <ChevronRight className="w-4 h-4" />
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        </div>
    );
  );
}
